kind: Secret
apiVersion: v1
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque
stringData:
  htpasswd: |
    ocpadmin:$2y$05$FB/pxJ4/BzMFqhNvoLCTlOWGE9RneTPATKLP6wuZqW7zUQX2sjET.