apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: gitea
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: bastion.${OCP_DOMAIN}:8443/ocp${OCP_VERSION}/rhtw/postgres:17.5
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: admin
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: gitea
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: gitea
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
