apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
    prometheusK8s:
      retention: 24h
      retentionSize: 5GB
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
    monitoringPlugin:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
    metricsServer:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
